version: '3.8'

services:
  pdf-extraction-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "${API_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - API_PORT=${API_PORT:-3000}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {r.statusCode === 200 ? process.exit(0) : process.exit(1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - pdf-api-network

networks:
  pdf-api-network:
    driver: bridge